### ISSUE TITLE
Timer expiration while offline.

### ISSUE THREAD

**Issue by Techhead0** [GinjaNinja32/bot32#9]
This is half-feature request, so I apologize in advance.

If one sets a timer with the bot, if it expires while offline you get no notification thereof. This likely also happens if one is online, but have changed nicks. Better behavior would be to inform one of the timer expiration when logging back on.

**Comment by GinjaNinja32** [comment]
with how timer works now there's no easy way to do this :c

edit: actually, I could hook it into message if that module is loaded... hm.
